// Sample catalogue for DeBu. The API seeds MongoDB from this file and the
// storefront uses it as an offline fallback when the API is unreachable.
//
// `art` drives the built-in illustrated product imagery (recoloured live by the
// customer's colour choice). Add real photos to `images` (e.g.
// "/images/products/ruby-bangles-1.jpg") and they take precedence.

const ALL = ['red', 'green', 'blue', 'pink', 'maroon', 'yellow', 'gold'];

/** @type {import('./index').Product[]} */
export const products = [
  // ───────────────────────────── Bangles ─────────────────────────────
  {
    id: 'bg-001',
    slug: 'royal-kundan-silk-bangles',
    name: 'Royal Kundan Silk Bangles',
    type: 'jewellery',
    category: 'bangles',
    price: 449,
    compareAtPrice: 549,
    description:
      'A pair of densely wrapped silk-thread bangles crowned with hand-set kundan stones and a gold zari border. Lightweight enough for all-day wedding wear.',
    highlights: ['Set of 2 bangles', 'Hand-set kundan stones', 'Sizes 2.2 to 2.10 available', 'Anti-tarnish base'],
    colors: ALL,
    defaultColor: 'maroon',
    art: { kind: 'bangle', variant: 0 },
    images: [],
    rating: 4.9,
    reviews: 128,
    tags: ['bridal', 'kundan', 'bestseller'],
    badge: 'Bestseller',
    featured: true,
    inStock: true,
  },
  {
    id: 'bg-002',
    slug: 'haldi-marigold-bangle-set',
    name: 'Haldi Marigold Bangle Set',
    type: 'jewellery',
    category: 'bangles',
    price: 349,
    description:
      'Sunshine-bright bangles inspired by marigold garlands — made for haldi mornings. Finished with tiny mirror work and pearl beads.',
    highlights: ['Set of 4 bangles', 'Mirror & pearl detailing', 'Perfect for haldi & mehandi'],
    colors: ALL,
    defaultColor: 'yellow',
    art: { kind: 'bangle', variant: 1 },
    images: [],
    rating: 4.8,
    reviews: 86,
    tags: ['haldi', 'festive'],
    featured: true,
    inStock: true,
  },
  {
    id: 'bg-003',
    slug: 'bridal-chuda-silk-set',
    name: 'Bridal Chuda Silk Set',
    type: 'jewellery',
    category: 'bangles',
    price: 699,
    compareAtPrice: 849,
    description:
      'A grand 12-piece bridal chuda in silk thread with alternating kundan and plain bangles. Custom-made to your wrist size and outfit colour.',
    highlights: ['12-piece bridal set', 'Made to order in 3–5 days', 'Matching colour to your saree'],
    colors: ALL,
    defaultColor: 'red',
    art: { kind: 'bangle', variant: 2 },
    images: [],
    rating: 5,
    reviews: 64,
    tags: ['bridal', 'wedding'],
    badge: 'Bridal',
    inStock: true,
  },
  {
    id: 'bg-004',
    slug: 'pastel-pearl-thread-bangles',
    name: 'Pastel Pearl Thread Bangles',
    type: 'jewellery',
    category: 'bangles',
    price: 299,
    description:
      'Soft pastel silk bangles edged with ivory pearls — a graceful pick for engagements, baby showers and receptions.',
    highlights: ['Set of 2 bangles', 'Ivory pearl edging', 'Everyday comfort fit'],
    colors: ALL,
    defaultColor: 'pink',
    art: { kind: 'bangle', variant: 3 },
    images: [],
    rating: 4.7,
    reviews: 52,
    tags: ['pearl', 'pastel'],
    inStock: true,
  },
  {
    id: 'bg-005',
    slug: 'temple-zari-kada',
    name: 'Temple Zari Kada',
    type: 'jewellery',
    category: 'bangles',
    price: 399,
    description:
      'A bold, broad kada wrapped in silk and wound with antique-gold zari, inspired by South Indian temple jewellery.',
    highlights: ['Single statement kada', 'Antique zari winding', 'Pairs beautifully with silk sarees'],
    colors: ALL,
    defaultColor: 'green',
    art: { kind: 'bangle', variant: 4 },
    images: [],
    rating: 4.8,
    reviews: 41,
    tags: ['temple', 'kada'],
    inStock: true,
  },
  {
    id: 'bg-006',
    slug: 'rainbow-festive-bangle-stack',
    name: 'Rainbow Festive Bangle Stack',
    type: 'jewellery',
    category: 'bangles',
    price: 549,
    description:
      'Six colourful bangles you can stack and mix for Navratri, Diwali and every festival in between.',
    highlights: ['Set of 6 bangles', 'Mix-and-match colours', 'Stone-studded accent bangles'],
    colors: ALL,
    defaultColor: 'blue',
    art: { kind: 'bangle', variant: 5 },
    images: [],
    rating: 4.6,
    reviews: 37,
    tags: ['festive', 'navratri'],
    badge: 'New',
    inStock: true,
  },

  // ───────────────────────────── Necklaces ─────────────────────────────
  {
    id: 'nk-001',
    slug: 'rani-haar-bridal-necklace',
    name: 'Rani Haar Bridal Necklace',
    type: 'jewellery',
    category: 'necklaces',
    price: 1199,
    compareAtPrice: 1499,
    description:
      'A regal long haar in silk thread beads with a kundan-studded centre pendant and pearl drops. Designed to be the centrepiece of your bridal look.',
    highlights: ['Long bridal length', 'Kundan pendant with pearl drops', 'Adjustable silk dori'],
    colors: ALL,
    defaultColor: 'maroon',
    art: { kind: 'necklace', variant: 0 },
    images: [],
    rating: 4.9,
    reviews: 93,
    tags: ['bridal', 'kundan', 'bestseller'],
    badge: 'Bestseller',
    featured: true,
    inStock: true,
  },
  {
    id: 'nk-002',
    slug: 'temple-lakshmi-silk-necklace',
    name: 'Temple Lakshmi Silk Necklace',
    type: 'jewellery',
    category: 'necklaces',
    price: 749,
    description:
      'Silk-wrapped beads strung with a temple-style Lakshmi pendant in antique gold finish. A timeless South Indian classic.',
    highlights: ['Temple-style pendant', 'Choker-to-princess length', 'Matching earrings available'],
    colors: ALL,
    defaultColor: 'green',
    art: { kind: 'necklace', variant: 1 },
    images: [],
    rating: 4.8,
    reviews: 71,
    tags: ['temple', 'festive'],
    featured: true,
    inStock: true,
  },
  {
    id: 'nk-003',
    slug: 'haldi-pearl-choker',
    name: 'Haldi Pearl Choker',
    type: 'jewellery',
    category: 'necklaces',
    price: 599,
    description:
      'A snug choker of silk beads and freshwater-look pearls, finished with a floral centre motif — made for haldi and mehandi day.',
    highlights: ['Choker length', 'Pearl & silk bead mix', 'Floral centre motif'],
    colors: ALL,
    defaultColor: 'yellow',
    art: { kind: 'necklace', variant: 2 },
    images: [],
    rating: 4.7,
    reviews: 48,
    tags: ['haldi', 'choker'],
    inStock: true,
  },
  {
    id: 'nk-004',
    slug: 'sangeet-tassel-necklace',
    name: 'Sangeet Tassel Necklace',
    type: 'jewellery',
    category: 'necklaces',
    price: 649,
    description:
      'Playful silk tassels and gold beads that swing as you dance — the sangeet night statement piece.',
    highlights: ['Silk tassel drops', 'Gold-tone beads', 'Lightweight for dancing'],
    colors: ALL,
    defaultColor: 'pink',
    art: { kind: 'necklace', variant: 3 },
    images: [],
    rating: 4.6,
    reviews: 33,
    tags: ['sangeet', 'tassel'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'nk-005',
    slug: 'mango-mala-heritage-necklace',
    name: 'Mango Mala Heritage Necklace',
    type: 'jewellery',
    category: 'necklaces',
    price: 999,
    compareAtPrice: 1199,
    description:
      'A heritage mango-motif mala recreated in silk thread and kundan, layered for grandeur at weddings and receptions.',
    highlights: ['Mango (paisley) motifs', 'Layered look', 'Kundan highlights'],
    colors: ALL,
    defaultColor: 'red',
    art: { kind: 'necklace', variant: 4 },
    images: [],
    rating: 4.9,
    reviews: 57,
    tags: ['heritage', 'bridal'],
    inStock: true,
  },
  {
    id: 'nk-006',
    slug: 'minimal-silk-bead-mala',
    name: 'Minimal Silk Bead Mala',
    type: 'jewellery',
    category: 'necklaces',
    price: 449,
    description:
      'An elegant single-line mala of silk thread beads and gold spacers for poojas, office festivals and everyday grace.',
    highlights: ['Single line mala', 'Gold spacers', 'Great for gifting'],
    colors: ALL,
    defaultColor: 'blue',
    art: { kind: 'necklace', variant: 5 },
    images: [],
    rating: 4.5,
    reviews: 29,
    tags: ['minimal', 'everyday'],
    inStock: true,
  },

  // ───────────────────────────── Earrings ─────────────────────────────
  {
    id: 'er-001',
    slug: 'grand-silk-jhumkas',
    name: 'Grand Silk Jhumkas',
    type: 'jewellery',
    category: 'earrings',
    price: 399,
    compareAtPrice: 499,
    description:
      'Big, bell-shaped jhumkas wrapped in silk thread with kundan tops and a ring of pearl drops that dance with every move.',
    highlights: ['Large bell jhumka', 'Kundan stud top', 'Pearl drop rim'],
    colors: ALL,
    defaultColor: 'maroon',
    art: { kind: 'earring', variant: 0 },
    images: [],
    rating: 4.9,
    reviews: 152,
    tags: ['bridal', 'jhumka', 'bestseller'],
    badge: 'Bestseller',
    featured: true,
    inStock: true,
  },
  {
    id: 'er-002',
    slug: 'chandbali-thread-earrings',
    name: 'Chandbali Thread Earrings',
    type: 'jewellery',
    category: 'earrings',
    price: 349,
    description:
      'Crescent-moon chandbalis in silk thread with stone accents — festive glamour without the weight.',
    highlights: ['Crescent chandbali shape', 'Stone accents', 'Featherlight'],
    colors: ALL,
    defaultColor: 'gold',
    art: { kind: 'earring', variant: 1 },
    images: [],
    rating: 4.8,
    reviews: 67,
    tags: ['chandbali', 'festive'],
    inStock: true,
  },
  {
    id: 'er-003',
    slug: 'mini-jhumka-studs',
    name: 'Mini Jhumka Studs',
    type: 'jewellery',
    category: 'earrings',
    price: 179,
    description:
      'Petite jhumkas for everyday ethnic wear, college fests and office celebrations.',
    highlights: ['Mini size', 'Everyday wear', 'Hypoallergenic hooks'],
    colors: ALL,
    defaultColor: 'pink',
    art: { kind: 'earring', variant: 2 },
    images: [],
    rating: 4.7,
    reviews: 88,
    tags: ['everyday', 'jhumka'],
    inStock: true,
  },
  {
    id: 'er-004',
    slug: 'layered-tier-jhumkas',
    name: 'Layered Tier Jhumkas',
    type: 'jewellery',
    category: 'earrings',
    price: 449,
    description:
      'Two-tier jhumkas stacked with silk domes and gold beads — a showstopper for receptions.',
    highlights: ['Double tier design', 'Gold bead trims', 'Statement size'],
    colors: ALL,
    defaultColor: 'green',
    art: { kind: 'earring', variant: 3 },
    images: [],
    rating: 4.8,
    reviews: 45,
    tags: ['reception', 'statement'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'er-005',
    slug: 'pearl-drop-silk-earrings',
    name: 'Pearl Drop Silk Earrings',
    type: 'jewellery',
    category: 'earrings',
    price: 229,
    description:
      'Round silk-wrapped studs with a single pearl drop — understated elegance for engagements and poojas.',
    highlights: ['Round stud with pearl drop', 'Understated look', 'Great for gifting'],
    colors: ALL,
    defaultColor: 'blue',
    art: { kind: 'earring', variant: 4 },
    images: [],
    rating: 4.6,
    reviews: 39,
    tags: ['pearl', 'minimal'],
    inStock: true,
  },
  {
    id: 'er-006',
    slug: 'haldi-flower-jhumkas',
    name: 'Haldi Flower Jhumkas',
    type: 'jewellery',
    category: 'earrings',
    price: 299,
    description:
      'Floral-top jhumkas in sunny silk threads — pairs perfectly with your haldi outfit and flower jewellery.',
    highlights: ['Floral top', 'Bright haldi tones', 'Medium size'],
    colors: ALL,
    defaultColor: 'yellow',
    art: { kind: 'earring', variant: 5 },
    images: [],
    rating: 4.7,
    reviews: 42,
    tags: ['haldi', 'floral'],
    featured: true,
    inStock: true,
  },

  // ─────────────────────────── Forehead Pendants ───────────────────────────
  {
    id: 'fp-001',
    slug: 'kundan-maang-tikka',
    name: 'Kundan Maang Tikka',
    type: 'jewellery',
    category: 'forehead-pendants',
    price: 299,
    compareAtPrice: 379,
    description:
      'A classic round maang tikka with a silk-thread halo, kundan centre and a fringe of pearls.',
    highlights: ['Round kundan pendant', 'Pearl fringe', 'Adjustable chain with hook'],
    colors: ALL,
    defaultColor: 'maroon',
    art: { kind: 'tikka', variant: 0 },
    images: [],
    rating: 4.9,
    reviews: 76,
    tags: ['bridal', 'kundan', 'bestseller'],
    badge: 'Bestseller',
    featured: true,
    inStock: true,
  },
  {
    id: 'fp-002',
    slug: 'teardrop-bridal-tikka',
    name: 'Teardrop Bridal Tikka',
    type: 'jewellery',
    category: 'forehead-pendants',
    price: 349,
    description:
      'An elegant teardrop tikka in silk and stones — graceful for brides and bridesmaids alike.',
    highlights: ['Teardrop pendant', 'Stone studded', 'Lightweight'],
    colors: ALL,
    defaultColor: 'red',
    art: { kind: 'tikka', variant: 1 },
    images: [],
    rating: 4.8,
    reviews: 44,
    tags: ['bridal', 'teardrop'],
    inStock: true,
  },
  {
    id: 'fp-003',
    slug: 'sun-motif-silk-tikka',
    name: 'Sun Motif Silk Tikka',
    type: 'jewellery',
    category: 'forehead-pendants',
    price: 249,
    description:
      'A radiant sun-motif tikka for festivals and dance performances, with silk petals around a gold centre.',
    highlights: ['Sun petal design', 'Festival favourite', 'Dance-safe clasp'],
    colors: ALL,
    defaultColor: 'yellow',
    art: { kind: 'tikka', variant: 2 },
    images: [],
    rating: 4.6,
    reviews: 31,
    tags: ['festive', 'dance'],
    inStock: true,
  },
  {
    id: 'fp-004',
    slug: 'passa-side-matha-patti',
    name: 'Passa Side Matha Patti',
    type: 'jewellery',
    category: 'forehead-pendants',
    price: 399,
    description:
      'A side-worn passa with layered silk chains and a statement pendant — a regal touch for the modern bride.',
    highlights: ['Side passa style', 'Layered chains', 'Statement pendant'],
    colors: ALL,
    defaultColor: 'pink',
    art: { kind: 'tikka', variant: 3 },
    images: [],
    rating: 4.7,
    reviews: 22,
    tags: ['bridal', 'passa'],
    badge: 'New',
    inStock: true,
  },
  {
    id: 'fp-005',
    slug: 'petite-pearl-tikka',
    name: 'Petite Pearl Tikka',
    type: 'jewellery',
    category: 'forehead-pendants',
    price: 199,
    description:
      'A dainty tikka with a small silk-wrapped disc and pearl drop — ideal for little ones, bridesmaids and festivals.',
    highlights: ['Petite size', 'Single pearl drop', 'Great for kids & bridesmaids'],
    colors: ALL,
    defaultColor: 'green',
    art: { kind: 'tikka', variant: 4 },
    images: [],
    rating: 4.7,
    reviews: 28,
    tags: ['petite', 'kids'],
    inStock: true,
  },

  // ───────────────────────────── Wire Bags ─────────────────────────────
  {
    id: 'wb-001',
    slug: 'classic-basket-wire-bag',
    name: 'Classic Basket Wire Bag',
    type: 'wire-bag',
    category: 'wire-bags',
    price: 299,
    sizes: [
      { size: 'small', price: 299, dimensions: '8" × 6" × 4"' },
      { size: 'medium', price: 449, dimensions: '11" × 8" × 5"' },
      { size: 'large', price: 599, dimensions: '14" × 10" × 6"' },
    ],
    description:
      'Our signature hand-woven wire basket bag with sturdy twin handles — perfect for temple visits, return gifts and daily shopping.',
    highlights: ['Hand-woven PVC wire', 'Washable & durable', 'Twin sturdy handles'],
    colors: ALL,
    defaultColor: 'pink',
    art: { kind: 'wirebag', variant: 0 },
    images: [],
    rating: 4.9,
    reviews: 112,
    tags: ['basket', 'bestseller'],
    badge: 'Bestseller',
    featured: true,
    inStock: true,
    customizationNotes: 'Choose up to two colours for the weave. Name initials can be woven on Medium & Large.',
  },
  {
    id: 'wb-002',
    slug: 'diamond-weave-tote',
    name: 'Diamond Weave Tote',
    type: 'wire-bag',
    category: 'wire-bags',
    price: 349,
    sizes: [
      { size: 'small', price: 349, dimensions: '9" × 7" × 4"' },
      { size: 'medium', price: 499, dimensions: '12" × 9" × 5"' },
      { size: 'large', price: 649, dimensions: '15" × 11" × 6"' },
    ],
    description:
      'An elegant tote with a diamond-lattice weave and contrast border. Roomy, stylish and made to last for years.',
    highlights: ['Diamond lattice pattern', 'Contrast border', 'Flat sturdy base'],
    colors: ALL,
    defaultColor: 'blue',
    art: { kind: 'wirebag', variant: 1 },
    images: [],
    rating: 4.8,
    reviews: 64,
    tags: ['tote', 'lattice'],
    featured: true,
    inStock: true,
    customizationNotes: 'Pick main and border colours. Zip lining available on request.',
  },
  {
    id: 'wb-003',
    slug: 'return-gift-mini-bag',
    name: 'Return Gift Mini Bag',
    type: 'wire-bag',
    category: 'wire-bags',
    price: 199,
    sizes: [
      { size: 'small', price: 199, dimensions: '6" × 5" × 3"' },
      { size: 'medium', price: 299, dimensions: '8" × 6" × 4"' },
      { size: 'large', price: 399, dimensions: '10" × 8" × 4"' },
    ],
    description:
      'Cute, colourful bags loved as return gifts for weddings, housewarmings and haldi functions. Bulk orders welcome.',
    highlights: ['Bulk pricing on 25+ pieces', 'Festive colour mixes', 'Custom tags available'],
    colors: ALL,
    defaultColor: 'yellow',
    art: { kind: 'wirebag', variant: 2 },
    images: [],
    rating: 4.9,
    reviews: 98,
    tags: ['return-gift', 'bulk'],
    badge: 'Gift Favourite',
    inStock: true,
    customizationNotes: 'Mention the event, quantity and colour mix. We can add name tags for bulk orders.',
  },
  {
    id: 'wb-004',
    slug: 'striped-market-bag',
    name: 'Striped Market Bag',
    type: 'wire-bag',
    category: 'wire-bags',
    price: 329,
    sizes: [
      { size: 'small', price: 329, dimensions: '9" × 7" × 5"' },
      { size: 'medium', price: 479, dimensions: '12" × 9" × 6"' },
      { size: 'large', price: 629, dimensions: '16" × 12" × 7"' },
    ],
    description:
      'Bold horizontal stripes in two colours on a roomy market bag that carries veggies, flowers and pooja items with ease.',
    highlights: ['Two-colour stripes', 'Extra roomy', 'Reinforced base'],
    colors: ALL,
    defaultColor: 'green',
    art: { kind: 'wirebag', variant: 3 },
    images: [],
    rating: 4.7,
    reviews: 51,
    tags: ['market', 'stripes'],
    inStock: true,
    customizationNotes: 'Choose two stripe colours. Handle length can be customised.',
  },
  {
    id: 'wb-005',
    slug: 'pooja-thali-wire-basket',
    name: 'Pooja Thali Wire Basket',
    type: 'wire-bag',
    category: 'wire-bags',
    price: 279,
    sizes: [
      { size: 'small', price: 279, dimensions: '8" × 8" × 4"' },
      { size: 'medium', price: 399, dimensions: '10" × 10" × 5"' },
      { size: 'large', price: 529, dimensions: '12" × 12" × 6"' },
    ],
    description:
      'A wide-mouthed wire basket for carrying pooja thalis, flowers and prasadam to the temple.',
    highlights: ['Wide square base', 'Holds a full thali', 'Easy to clean'],
    colors: ALL,
    defaultColor: 'maroon',
    art: { kind: 'wirebag', variant: 4 },
    images: [],
    rating: 4.8,
    reviews: 43,
    tags: ['pooja', 'temple'],
    inStock: true,
    customizationNotes: 'Gold accent weave available at no extra cost.',
  },
  {
    id: 'wb-006',
    slug: 'designer-lunch-bag',
    name: 'Designer Lunch Bag',
    type: 'wire-bag',
    category: 'wire-bags',
    price: 249,
    sizes: [
      { size: 'small', price: 249, dimensions: '7" × 6" × 5"' },
      { size: 'medium', price: 349, dimensions: '9" × 7" × 6"' },
      { size: 'large', price: 449, dimensions: '11" × 8" × 7"' },
    ],
    description:
      'A compact designer bag for lunch boxes and daily essentials, woven with a playful chevron pattern.',
    highlights: ['Chevron weave', 'Fits standard tiffin boxes', 'Everyday durable'],
    colors: ALL,
    defaultColor: 'red',
    art: { kind: 'wirebag', variant: 5 },
    images: [],
    rating: 4.6,
    reviews: 36,
    tags: ['lunch', 'everyday'],
    badge: 'New',
    inStock: true,
    customizationNotes: 'Add an insulated lining for ₹60 (mention in notes).',
  },
];

/** Jewellery combos. `originalPrice` is derived from the included products. */
const comboDefinitions = [
  {
    id: 'cb-001',
    slug: 'bridal-combo',
    name: 'Bridal Combo',
    tagline: 'Everything the bride needs — perfectly matched.',
    description:
      'Our most-loved bridal trio: the Rani Haar necklace, Grand Silk Jhumkas and Bridal Chuda set, all custom-made in the colour of your wedding saree.',
    itemSlugs: ['rani-haar-bridal-necklace', 'grand-silk-jhumkas', 'bridal-chuda-silk-set'],
    price: 1899,
    colors: ALL,
    defaultColor: 'maroon',
    art: { kind: 'combo', variant: 0 },
    badge: 'Most Loved',
  },
  {
    id: 'cb-002',
    slug: 'festival-combo',
    name: 'Festival Combo',
    tagline: 'Shine through every festival of the year.',
    description:
      'Temple Lakshmi necklace, Royal Kundan bangles and Kundan Maang Tikka — a festive trio for Diwali, Pongal, Navratri and poojas.',
    itemSlugs: ['temple-lakshmi-silk-necklace', 'royal-kundan-silk-bangles', 'kundan-maang-tikka'],
    price: 1249,
    colors: ALL,
    defaultColor: 'green',
    art: { kind: 'combo', variant: 1 },
    badge: 'Festive Pick',
  },
  {
    id: 'cb-003',
    slug: 'haldi-combo',
    name: 'Haldi Sunshine Combo',
    tagline: 'Bright, joyful and made for the haldi ceremony.',
    description:
      'Haldi Pearl Choker, Haldi Flower Jhumkas and Haldi Marigold Bangles in radiant sunshine tones.',
    itemSlugs: ['haldi-pearl-choker', 'haldi-flower-jhumkas', 'haldi-marigold-bangle-set'],
    price: 1049,
    colors: ALL,
    defaultColor: 'yellow',
    art: { kind: 'combo', variant: 2 },
    badge: 'Haldi Special',
  },
];

const bySlug = new Map(products.map((p) => [p.slug, p]));

/** @type {import('./index').Combo[]} */
export const combos = comboDefinitions.map((c) => {
  const items = c.itemSlugs.map((slug) => {
    const p = bySlug.get(slug);
    if (!p) throw new Error(`Combo ${c.slug} references unknown product ${slug}`);
    return { slug: p.slug, name: p.name, category: p.category, price: p.price };
  });
  const originalPrice = items.reduce((sum, i) => sum + i.price, 0);
  return {
    ...c,
    type: 'combo',
    category: 'combos',
    items,
    originalPrice,
    savings: originalPrice - c.price,
    images: [],
    inStock: true,
  };
});
